apiVersion: batch/v1
kind: Job
metadata:
  name: gimme-pi-up-to-n-digits
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(REPLACE_ME_DADDY)"]
      restartPolicy: Never
  backoffLimit: 4
